i3xrocks.conf
scripts/battery2
scripts/cpu_usage
scripts/keyboard_layout
scripts/nm-vpn
scripts/time
scripts/wifi2

This adds a few new blocklets to enhance the default set of blocklets.
Not sure about the colour on the Battery2 blocklet yet, but it's at least a handy visual guide for myself to remember to charge my laptop.
The Battery2 blocklet also supports multiple batteries which is something the default Battery blocklet doesn't.

Add nm-vpn, battery, wifi and keyboard layout blocklet

---

debian/changelog
scripts/wifi2

fixes regolith-linux/regolith-desktop#122
This is using a more modern commandline tool for network device discovery and management.
Works nicely with UTF-8 and requires less messing around in `/proc/` and `/sys/`
It does have this weird delay when it runs for the first time in a while, but not sure it matters much.

Update Wifi2 blocklet to use nmcli

---

scripts/nm-vpn

This one did not work for me using nordvpn. since it is called :tun:tun0 instead of :vpn:tun0. I also added support for wireguard and added a fancy icon :) Note that we must update the .Xresources file to add a green color to it in the i3xblock.vpn.color variable. (or just default grey color if we rather want that. I use a green color so that it is easier to see that im in "secure" mode)

add wireguard support and fancy icon

---

Makefile
debian/copyright
i3xrocks.conf
scripts/focused-window-name

This is I think my third pull request ever and the first one on a new function rather then just a tweak so I'm not sure if I did this right ...
Anyway, the script returns the title of the focused window. The short version is not really smart, but at least is short. It can also be used with command line arguments. I'm not sure this feature will be useful for anything, but I coded it with that first and then realized I need to use environment variables if I want a nice config in i3xrocks.

adding focused-window-name to show title of focused window

---

config

By default, base on the script in `battery3` it will look for any device as per this line:
```bash
BATT_DEVICE=$(upower -e | grep -o 'BAT[0-9]' | head -n 1)
```
Removing the `instance=BAT0` in the sample config will still work.
If defined, it will use the one that is set by the user as per this line: `BLOCK_INSTANCE`
```bash
__UPOWER_INFO=$(upower --show-info "/org/freedesktop/UPower/devices/battery_${BLOCK_INSTANCE:-$BATT_DEVICE}")
```

Remove instance value in battery3

---

scripts/weather

This pull request is an attempt to address the open enchantment found [here](https://github.com/regolith-linux/regolith-desktop/issues/242).
It simply adds a weather block to i3xblocks.  This block pulls data from wttr.in.  It will show the temperature based upon the user's IP address location, along with an emoji representing the weather.  The temperature unit will be based upon the preferred unit of the location's country.

Added weather block

---

scripts/disk

This shows the disk usage for a given mount point
The block declaration follows:
`
[disk]
command=~/.config/regolith/i3blocks/disk
LABEL=home
MNT=/home
interval=60
`

disk usage block

---

scripts/volume

My system reports two audio values, i.e.:
`amixer -D pulse get Master`
```
Simple mixer control 'Master',0
Capabilities: pvolume pswitch pswitch-joined
Playback channels: Front Left - Front Right
Limits: Playback 0 - 65536
Mono:
Front Left: Playback 15309 [23%] [on]
Front Right: Playback 15309 [23%] [on]
```
This change proposes to just take the first. I don't know if this is good practice or not, would appreciate any input.

Take only first volume and status from amixer

---

scripts/volume

Replaces lsmod check with `pactl list` return code. On my distro, pulse doesn't appear in lsmod. Similarly, just check the retcode for grep rather than doing a string substitution
Again, this might not be the best fix, e.g. what if pulse audio is installed, but lists no sinks/devices etc.

Determine pulseaudio using `pactl list`

---

scripts/nm-vpn

I made a few changes to the part of the script detecting and choosing the right vpn connection name.
Here is a working example from nmcli:
```MY_VPN:ID1:vpn:wlo1
MY_WIFI:ID2:802-11-wireless:wlo1
vpn0:ID3:tun:vpn0
docker0:ID4:bridge:docker0
```
With the previous version, I got none. The new one finds and selects `MY_VPN`. But I am not sure about other test cases, especially with wireguard.

Change awk logic to detect right connection name.

---

scripts/media-player

This PR fixes the width of the output field to 25 characters. The original script depending on the song title and artists sometimes could take up the whole bar since there was no limit! This will takes care of it. If the output exceeds 25 characters it will add 3 dots to show that the text is cut off

fixed width output

---

conf.d/10_focused-window-name

Windows names were wrongly including the string `uncomment to show an icon`

Fix focused-window-name plugin

---

scripts/keyboard-layout

The `sources` parameters is what works for me. `mru-sources` parameter is empty causing the block to display non-sense.

Udpated gsetting parameter lookup

---

scripts/volume

This relatively localized PR actually changes many things in the volume blocklet. I do not expect all of the changes to be included upstream, so I have separated the changes in different commits, in order to make it easier to pick what to include, in a way.
- `STEP`, `UNIT` and `MIXER` are now searched in `XResources` definitions before falling back to the default values. The three relevant definitions are `i3xrocks.volume.step`, `i3xrocks.volume.unit` and `i3xrocks.volume.mixer`.
- The volume level is now displayed even if the control is muted. There are two reasons for this:
- The blocklet size stays consistent when muting/unmuting.
- It can be useful to know the volume level before unmuting.
- The volume level is displayed in warning color when muted, to better highlight the reason the …

Updates to the volume blocklet script

---

scripts/focused-window-name

Somehow name could end up being None throwing an attribute error when trying to split. Wrapped it in an except block to catch it.

fixed an error with name somehow being None

---

debian/changelog
debian/control

The 2nd entry in the changelog is from another commit, please ignore.

Update i3xrocks-focused-window-name to use consistent python library name

---

scripts/focused-window-name

Some windows do not have names and every time I get a Ubuntu crash dialog for this script. Now the script checks if `name` is actually a string.

Exit gracefully if the focused window does not have a name

---

scripts/memory

This change sets the amount of free memory from the `MemAvailable` field
of `/proc/meminfo` when it is available.  If not available, the existing behavior
acts as a fall-back. This field is available in Linux kernels since early 2014.
To quote the documentation, `MemAvailable` is:
> An estimate of how much memory is available for starting new
> applications, without swapping. Calculated from MemFree,
> SReclaimable, the size of the file LRU lists, and the low
> watermarks in each zone.
> The estimate takes into account that the system needs some
> page cache to function well, and that not all reclaimable
> slab will be reclaimable, due to items being in use. The
> impact of those factors will vary from system to system.
Reference: …

Use `MemAvailable` to indicate memory usage

---

scripts/battery

This is a fix for issue #77 . It adds support for showing aggregate battery percentage for 1 or more batteries. It relies on upower's [DisplayDevice](https://upower.freedesktop.org/docs/UPower.html#id-1.2.3.8.5).
If a user prefers to show a specific battery (e.g. battery_BAT0) they can do so by setting `BLOCK_INSTANCE` to `battery_BAT0`.
The `get_battery_percent` function has also been improved to handle cases where the returned percentage is float with a comma used as a floating point separator.

[IMPR] Show aggregated battery percentage

---

scripts/net-traffic

Fixes issue #73 by setting the value of RN, TN and AN to 0 instead of exiting if the value is 0 or invalid.

[FIX] Fixes dissapearing indicator when value is 0

---

scripts/focused-window-name

Fixes the following crash:
```
Traceback (more recent call last):
File "/usr/share/i3xrocks/focused-window-name", line 78, in <module>
if "LibreOffice" in name.split("-")[-1] and instance == "libreoffice":
AttributeError: 'NoneType' object has no attribute 'split'
```

Fix crash when focused window name is None

---

scripts/battery

The current command removes numbers in the format `##,###`; however, my computer's output is `##.###` so I added an additional `cut` command to remove both types of decimals. Note, it doesn't round.
[before]
[after]

Remove decimal places from battery number

---

scripts/net-traffic

Previously, the button handling was run before the variable `INT_TYPE` was initialized. This should've been detected earlier (especially by `shellcheck`) but wasn't. With the recently added tests the script should now run "flawlessly".
I've also exchanged the default route parsing logic for a shorter, more efficient one-liner.

Fix for button handling of the net-traffic script

---

scripts/volume

This was broken in https://github.com/regolith-linux/regolith-i3xrocks-config/commit/2bfab21c15a9d730aaf9885bd777122f2ef72c16#diff-18e70f7d8538e1b83ef4439d10ed0ac98c433f6551932b2d172544b23b84b637
Also add overrides for every possible action (left, middle, right mouse buttons and scrolling actions)

Restore original behavior of mouse actions on volume

---

scripts/next-workspace

This pull request fixes the bug reported in https://github.com/regolith-linux/regolith-desktop/issues/470 as it will now use `xrdb -query` to read the workspace names directly from the configurations set by regolith. This also means we can deprecate the `--startnum` flag, since we can now read the smallest workspace number from the configs.

reading from xresources now

---

conf.d/50_disk-capacity

The script is looking for uppercase MNT, not lowercase mnt.

Match example with what the script is looking for

---

.github/workflows/test.yml
conf.d/30_net-traffic
scripts/net-traffic
tests/net-traffic_test.sh

Completely rewrote the net-traffic script (well, almost) to use `numfmt` instead of coming up with our own routine. Also uses `sysfs` instead of `proc` filtering now to determine the device type (with potential to add more devices) and traffic deltas.
Also added tests, which are regexp-based for now, but better than nothing.

Rewrote net-traffic script, fixes #91

---

scripts/weather

I live in Vienna, Austria, and noticed that the weather block did not match with current conditions in my area. I did some digging, and it seems that  `IP_LOCATION` was being set to "Vienna,Vienna" (since Vienna the city is also [Vienna the region](https://en.wikipedia.org/wiki/States_of_Austria)). When passed to the wttr.in service, this returns information about Vienna, South Dakota ([https://wttr.in/Vienna%2CVienna](https://wttr.in/Vienna%2CVienna)).
Adding the country code to the request is not enough to resolve this ambiguity, which I tested using a VPN set to a location in the USA. This gave me a location of "Clifton,New Jersey,US". The weather service returns the weather for Clifton in California: [https://wttr.in/Clifton%2CNew%20Jersey%2CUS](https://wttr.in/Clifton%2CNew%20Jersey%2 …

Add extra location information to weather API request

---

scripts/memory

Memory rock on click event was not functioning due to a missing initialization of the BUTTON variable.

Fix click event in memory rock

---

scripts/memory

Memory rock default full text shows memory available, while swap shows the one currently in use.
This aligns the default full text to the swap behavior.
It may be a matter of preference, but I feel like showing the memory currently in use is what a user would expect from this rock.

Change memory rock default full text

---

.github/workflows/test.yml
scripts/disk-capacity
tests/disk-capacity_test.sh
tests/fixtures/disk-capacity/first/df
tests/fixtures/disk-capacity/second/df

`disk-capacity` is using `sh`, which doesn't support the syntax added for the button click guard. Fixed by using `bash` instead.
Also slightly changed the way we're getting the free capacity to be less cumbersome to parse and only use `awk` instead of `grep` _and_ `awk`.
Also added tests.

Fix disk-capacity button clicks, add tests

---

.github/workflows/test.yml
scripts/temp
tests/fixtures/temp/third/sensors
tests/temp_test.sh

The default `awk` for `focal` is `nawk`, but for folks that want to install `gawk` instead (which overrides this default choice) we need to verify that the tests (and scripts therefore)  are working as well. The differences are subtle, but can "make or break" the experience for some users.
Fixes #107

Added gawk specific testing for temp script

---

scripts/net-traffic
tests/fixtures/net-traffic/first/ip
tests/fixtures/net-traffic/second/ip
tests/net-traffic_test.sh

By default, VPN interfaces are showing up as default routes on the `main` table because they can be set as the default destination for traffic, while the actual, physical device (e.g. `eth0`) sits back as a sort of "shadow" default device (which is still necessary, otherwise you wouldn't be able to talk to your router/the Internet anymore). Unfortunately, this can cause the command `ip route show default` (which queries the  `main` table) to return multiple entries, including the VPN-bound default routes. Previously we tried to work around this by just cutting the output to a single line and taking whatever was returned. Unfortunately, that's not reliable enough (see the `ip` mocks I added for both, `tun0` and `ppp0` default routes) as the output slightly differs and makes parsing the …

Filter VPN interfaces from net-traffic scripts

---

debian/changelog
scripts/net-traffic

Capture error cases involving invalid network device paths and sleep before returning to resolve CPU consuming loop due to  interval type of i3blocks.  Addresses https://github.com/regolith-linux/regolith-desktop/issues/532.
1. On local machine, observe issue when disabling wifi.  
2. Replace `release` version of `net-traffic` script with this
3. disable and renable wifi
4. observe no obvious increase load on machine based on network connectivity state

net-traffic cpu load w/ no or invalid network devices fix

---

conf.d/80_updates
debian/i3xrocks-updates.install
scripts/updates

This adds a block to check for package updates
In this screenshot there are a total of 12 updates available, 3 of which are security updates
- `i3xrocks.updates.checkcmd` : command to run to get the number of updates should return in format '<total_updates>;<security_updates>'
- `i3xrocks.updates.displayzero` : bool, if true display even if there are zero updates
- `i3xrocks.action.updates` : command to run when block is left clicked
- `i3xrocks.action.updates.reboot` : command to run when block is left clicked and reboot is required
- `i3xrocks.label.updates` : glyph icon to display
- `i3xrocks.label.updates.reboot` : glyph icon to display when reboot is required
- `i3xrocks.updates.interval` : interval in seconds between checks

Add updates block

---

scripts/nm-vpn

There are currently two space characters between the icon and the name of the VPN connection.
All other scripts only have a single space. This removes the extra space to make it consistent with the other scripts.

Remove extra space in nm-vpn output

---

scripts/microphone
scripts/volume

This PR fixes #135, which describes the issue that if the volume or microphone level is below 10 no value is displayed in the status bar.
Altered the `sed`-regex within the `mixer_value` function to also include single-digit values and extended the if-logic to prepend a zero if the value s below 10 to avoid bar shift / jumping output in the volume and microphone script.
Successfully tested both scripts in a virtual machine (Ubuntu server 22.04 LTS with regolith set up like it's described here: [https://regolith-desktop.com/docs/howtos/minimal-ubuntu-install/](https://regolith-desktop.com/docs/howtos/minimal-ubuntu-install/)).

Fixed volume and microphone mixer_value to display values below 10 and prepend a zero if value is below 10

---

scripts/volume

Extracting these functions enables individuals to easily reconfigure the bindings. I use natural scrolling (inverse) for my mouse wheel. I would, however, prefer to crank up the volume by using wheel-up (non-inverse) mode. I can now accomplish this via:
```Xresource
i3xrocks.action.volume.scrollup: volume_down
i3xrocks.action.volume.scrolldn: volume_up
```

volume: extract toggle, volume_up, volume_down functions

---

scripts/bluetooth

When an alias for a bluetooth device has been set (for example, with `bluetoothctl set-alias ...`), we can use it instead of the device's full name.
There are no tests for the bluetooth script yet.
This is a very small touch, so no tests have been added here either.

Try to use bluetooth device alias instead of name

---

scripts/keyboard-layout

Hi :wave:,
I installed Regolith Linux 2.2 from the ISO [here](https://regolith-desktop.com/#get-regolith-22) today. After inspecting the `i3xrocks-keyboard-layout` package, I found that the left click action links to the wrong gnome settings menu:
From my understanding it makes more sense to link to the keyboard layout settings here:
I assume the menu setting entries were changed upstream. Correct me if I am wrong. Let me know if you want anything changed.

fix(keyboard-layout): open keyboard menu instead

---

scripts/battery

I think this fixes a layout error. All i3xrocks indicator values are shown with `xrescat i3xrocks.value.color` except for battery. The battery script uses `xrescat i3xrocks.label.color`. This change fixes it. 
I've made this change for my own setup and think maybe others will like it too.

Use value colors for battery percentage and charge

---

scripts/media-player

When we truncate the media-player's artist and track title it would be nice to show as much of it as possible.
Previously we chop 4 and 5 characters off of the artist and track respectively for the spacing and ellipsis as `...`.
This PR simply uses the unicode ellipsis character `…` U+2026 so we only have to chop 2 and 3 characters off!

Use a … instead of ... to show more of the artist and title

---

scripts/volume

The volume script attempts to detect pulseaudio by calling `pactl`. On machines without `pactl` installed, the detection generates a steady stream of noise in the logs, `journalctl --follow` shows:
```
regolith-session-x11[4037999]: /usr/share/i3xrocks/scripts/volume: line 38: pactl: command not found
```
Closes #154.

volume: avoid logging error while detecting pulseaudio
