scripts/nettraffic
I added two function for font and label span to make the easier to read and fixed the net icon issue
=> Fixed the net icon issue

scripts/temperature2
Adding a new temperature script that uses the _value, warning_ and _critical_ colors from the color scheme.
=> Adding a script temperature2 that follows the selected color scheme

.gitignore, scripts/nettraffic
I tried to fix the negative speed issue but I have no way of testing it! I also checked the script with [shellcheck](https://www.shellcheck.net/) and fixed the issues.
=> Resolve negative speed issue

scripts/nm-vpn
This simple modification adds support for tap devices, may be useful also to other users.
=> Added support for tap0

scripts/battery
As mentioned in [PR #38](https://github.com/regolith-linux/regolith-i3xrocks-config/pull/38), I am redoing this PR including only the cleanup part.
=> Script cleanup

conf.d/30_net-traffic, scripts/net-traffic
Adapted from:
https://github.com/marssantoso/nettraffic/commit/c2377279ec8f0d4c287c2dd2777c8d720e6ca2c2
=> Add option for net-traffic to display data in bits rather than bytes.

scripts/battery, scripts/net-traffic, scripts/time, scripts/wifi
- Also fix network bandwidth calculation/shellcheck errors
in net-traffic script
Fixes https://github.com/regolith-linux/regolith-desktop/issues/336
=> Fix button clicks blocklets

scripts/bluetooth
python2 dependencies: [**bluetool**](https://pypi.org/project/bluetool/)
Fixes #57
=> Added bluetooth blocklet

scripts/net-traffic
Fixes https://github.com/regolith-linux/regolith-i3xrocks-config/pull/56#issuecomment-633782877
=> Removed verbose output from net-traffic script

scripts/weather
...and fallback to country locale if unspecified. 
Based on https://github.com/regolith-linux/regolith-desktop/issues/372.
=> Add ability to specify temperature unit via xres

scripts/weather
- Put curl for weather in double quotes as the `&format` wasn't being passed properly and returned multiple lines
- download this branch
- run `weather` from the command line
- see that the output is on one line
=> Make curl work for special characters

conf.d/90_time
I forgot to push this config earlier. Now that i3xrocks **config files** are xresource-aware the bar can be configured like this.
=> Make time interval configurable with Xresource

scripts/bluetooth
well, bluetooth text didn't obey the formatting of other bar elements!
now it will
=> format the connected device string using pango same as other rocks

.github/workflows/test.yml, scripts/weather, tests/fixtures/weather/first/curl, tests/weather_test.sh
Here's a (opinionated) rewrite of the weather blocklet:
1. **Don't** do our own IP "magic", wttr.in does this for us, and it's much more reliable and way easier to do. If it doesn't detect it properly you can still set `weather_location` to something sensible.
2. **Don't** do our own temperature unit "magic", again, wttr.in will select the "right" unit for us, depending on the location you're using it from (e.g. if you're using it from somewhere inside the US it'll choose to display Fahrenheit instead of Celsius). You can still set the `weather_unit` variable to either `u` (for [USCS](https://en.wikipedia.org/wiki/United_States_customary_units)) or `m` (for metric) to override this behavior.
3. **Definitely don't** use our "own" `urlencode` function in bash. There are a thousand edge …
=> Rewrite weather blocklet

scripts/net-traffic
… as net-traffic cannot use them w/ repeat interval type.
=> Remove button handling code

scripts/net-traffic
=> Use /proc/net/route for interface detection

scripts/focused-window-name
Adding xml escaping (plus some formatting that was auto-done by isort and black which I left in).
=> fixed xml escaping

scripts/temp, tests/fixtures/temp/fourth/sensors, tests/temp_test.sh
And run formatter.
Addresses #123 for now.
=> Add support to temp script for Tctl

conf.d/40_tailscale, debian/control, debian/copyright, debian/i3xrocks-tailscale.intall, scripts/tailscale
This will show the `tailscale` IP address if connected or enabled.
=> Add tailscale IP

scripts/updates
Addresses https://github.com/regolith-linux/regolith-i3xrocks-config/issues/133
=> replace reboot command with saner default

scripts/media-player
the default is to increase/decrease the volume by 5%
=> Add scrolling as inputs to media-player
